// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/card_entity.dart';
import 'data/models/transaction_entity.dart';
import 'data/models/wallet_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1983023830164191918),
    name: 'CardEntity',
    lastPropertyId: const obx_int.IdUid(10, 1227147406334190065),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2991068622925773667),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8939638582065041628),
        name: 'cardNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1737532006504336279),
        name: 'expiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4712016485363287639),
        name: 'cvc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2742521727171442863),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7115492839038352350),
        name: 'walletId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 5782537377068367520),
        relationField: 'wallet',
        relationTarget: 'WalletEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 171964542767835083),
        name: 'amount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3994105107040560353),
        name: 'themeColorLeft',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1227147406334190065),
        name: 'themeColorRight',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'transactions',
        srcEntity: 'TransactionEntity',
        srcField: 'card',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5824557919156728609),
    name: 'TransactionEntity',
    lastPropertyId: const obx_int.IdUid(7, 8899025939104159919),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5730433394771315683),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1826033378107106400),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5705987176027675343),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7591427843480241122),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 963323934833465662),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5810493280506337437),
        name: 'walletId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 2325352475308693927),
        relationField: 'wallet',
        relationTarget: 'WalletEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8899025939104159919),
        name: 'cardId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 2359422876437590617),
        relationField: 'card',
        relationTarget: 'CardEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7375780381033129542),
    name: 'WalletEntity',
    lastPropertyId: const obx_int.IdUid(3, 6668714892371084669),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2853411333254262377),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7483766484453442312),
        name: 'currency',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 8068262949654632148),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6668714892371084669),
        name: 'balance',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'cards',
        srcEntity: 'CardEntity',
        srcField: 'wallet',
      ),
      obx_int.ModelBacklink(
        name: 'transactions',
        srcEntity: 'TransactionEntity',
        srcField: 'wallet',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 7375780381033129542),
    lastIndexId: const obx_int.IdUid(4, 8068262949654632148),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [5769820451099573428],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CardEntity: obx_int.EntityDefinition<CardEntity>(
      model: _entities[0],
      toOneRelations: (CardEntity object) => [object.wallet],
      toManyRelations: (CardEntity object) => {
        obx_int.RelInfo<TransactionEntity>.toOneBacklink(
          7,
          object.id,
          (TransactionEntity srcObject) => srcObject.card,
        ): object.transactions,
      },
      getId: (CardEntity object) => object.id,
      setId: (CardEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CardEntity object, fb.Builder fbb) {
        final cardNumberOffset = fbb.writeString(object.cardNumber);
        final expiryDateOffset = fbb.writeString(object.expiryDate);
        final cvcOffset = fbb.writeString(object.cvc);
        final typeOffset = fbb.writeString(object.type);
        final themeColorLeftOffset = fbb.writeString(object.themeColorLeft);
        final themeColorRightOffset = fbb.writeString(object.themeColorRight);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cardNumberOffset);
        fbb.addOffset(2, expiryDateOffset);
        fbb.addOffset(3, cvcOffset);
        fbb.addOffset(4, typeOffset);
        fbb.addInt64(6, object.wallet.targetId);
        fbb.addInt64(7, object.amount);
        fbb.addOffset(8, themeColorLeftOffset);
        fbb.addOffset(9, themeColorRightOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final cardNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final expiryDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final cvcParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final themeColorLeftParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final themeColorRightParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final amountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = CardEntity(
          cardNumber: cardNumberParam,
          expiryDate: expiryDateParam,
          cvc: cvcParam,
          type: typeParam,
          themeColorLeft: themeColorLeftParam,
          themeColorRight: themeColorRightParam,
          amount: amountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.wallet.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.wallet.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<CardEntity>(
          object.transactions,
          store,
          obx_int.RelInfo<TransactionEntity>.toOneBacklink(
            7,
            object.id,
            (TransactionEntity srcObject) => srcObject.card,
          ),
        );
        return object;
      },
    ),
    TransactionEntity: obx_int.EntityDefinition<TransactionEntity>(
      model: _entities[1],
      toOneRelations: (TransactionEntity object) => [
        object.wallet,
        object.card,
      ],
      toManyRelations: (TransactionEntity object) => {},
      getId: (TransactionEntity object) => object.id,
      setId: (TransactionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final categoryOffset = fbb.writeString(object.category);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, categoryOffset);
        fbb.addFloat64(3, object.amount);
        fbb.addInt64(4, object.date.millisecondsSinceEpoch);
        fbb.addInt64(5, object.wallet.targetId);
        fbb.addInt64(6, object.card.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = TransactionEntity(
          title: titleParam,
          category: categoryParam,
          amount: amountParam,
          date: dateParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.wallet.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.wallet.attach(store);
        object.card.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.card.attach(store);
        return object;
      },
    ),
    WalletEntity: obx_int.EntityDefinition<WalletEntity>(
      model: _entities[2],
      toOneRelations: (WalletEntity object) => [],
      toManyRelations: (WalletEntity object) => {
        obx_int.RelInfo<CardEntity>.toOneBacklink(
          7,
          object.id,
          (CardEntity srcObject) => srcObject.wallet,
        ): object.cards,
        obx_int.RelInfo<TransactionEntity>.toOneBacklink(
          6,
          object.id,
          (TransactionEntity srcObject) => srcObject.wallet,
        ): object.transactions,
      },
      getId: (WalletEntity object) => object.id,
      setId: (WalletEntity object, int id) {
        object.id = id;
      },
      objectToFB: (WalletEntity object, fb.Builder fbb) {
        final currencyOffset = fbb.writeString(object.currency);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, currencyOffset);
        fbb.addFloat64(2, object.balance);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final balanceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = WalletEntity(
          currency: currencyParam,
          balance: balanceParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<WalletEntity>(
          object.cards,
          store,
          obx_int.RelInfo<CardEntity>.toOneBacklink(
            7,
            object.id,
            (CardEntity srcObject) => srcObject.wallet,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<WalletEntity>(
          object.transactions,
          store,
          obx_int.RelInfo<TransactionEntity>.toOneBacklink(
            6,
            object.id,
            (TransactionEntity srcObject) => srcObject.wallet,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CardEntity] entity fields to define ObjectBox queries.
class CardEntity_ {
  /// See [CardEntity.id].
  static final id = obx.QueryIntegerProperty<CardEntity>(
    _entities[0].properties[0],
  );

  /// See [CardEntity.cardNumber].
  static final cardNumber = obx.QueryStringProperty<CardEntity>(
    _entities[0].properties[1],
  );

  /// See [CardEntity.expiryDate].
  static final expiryDate = obx.QueryStringProperty<CardEntity>(
    _entities[0].properties[2],
  );

  /// See [CardEntity.cvc].
  static final cvc = obx.QueryStringProperty<CardEntity>(
    _entities[0].properties[3],
  );

  /// See [CardEntity.type].
  static final type = obx.QueryStringProperty<CardEntity>(
    _entities[0].properties[4],
  );

  /// See [CardEntity.wallet].
  static final wallet = obx.QueryRelationToOne<CardEntity, WalletEntity>(
    _entities[0].properties[5],
  );

  /// See [CardEntity.amount].
  static final amount = obx.QueryIntegerProperty<CardEntity>(
    _entities[0].properties[6],
  );

  /// See [CardEntity.themeColorLeft].
  static final themeColorLeft = obx.QueryStringProperty<CardEntity>(
    _entities[0].properties[7],
  );

  /// See [CardEntity.themeColorRight].
  static final themeColorRight = obx.QueryStringProperty<CardEntity>(
    _entities[0].properties[8],
  );

  /// see [CardEntity.transactions]
  static final transactions =
      obx.QueryBacklinkToMany<TransactionEntity, CardEntity>(
        TransactionEntity_.card,
      );
}

/// [TransactionEntity] entity fields to define ObjectBox queries.
class TransactionEntity_ {
  /// See [TransactionEntity.id].
  static final id = obx.QueryIntegerProperty<TransactionEntity>(
    _entities[1].properties[0],
  );

  /// See [TransactionEntity.title].
  static final title = obx.QueryStringProperty<TransactionEntity>(
    _entities[1].properties[1],
  );

  /// See [TransactionEntity.category].
  static final category = obx.QueryStringProperty<TransactionEntity>(
    _entities[1].properties[2],
  );

  /// See [TransactionEntity.amount].
  static final amount = obx.QueryDoubleProperty<TransactionEntity>(
    _entities[1].properties[3],
  );

  /// See [TransactionEntity.date].
  static final date = obx.QueryDateProperty<TransactionEntity>(
    _entities[1].properties[4],
  );

  /// See [TransactionEntity.wallet].
  static final wallet = obx.QueryRelationToOne<TransactionEntity, WalletEntity>(
    _entities[1].properties[5],
  );

  /// See [TransactionEntity.card].
  static final card = obx.QueryRelationToOne<TransactionEntity, CardEntity>(
    _entities[1].properties[6],
  );
}

/// [WalletEntity] entity fields to define ObjectBox queries.
class WalletEntity_ {
  /// See [WalletEntity.id].
  static final id = obx.QueryIntegerProperty<WalletEntity>(
    _entities[2].properties[0],
  );

  /// See [WalletEntity.currency].
  static final currency = obx.QueryStringProperty<WalletEntity>(
    _entities[2].properties[1],
  );

  /// See [WalletEntity.balance].
  static final balance = obx.QueryDoubleProperty<WalletEntity>(
    _entities[2].properties[2],
  );

  /// see [WalletEntity.cards]
  static final cards = obx.QueryBacklinkToMany<CardEntity, WalletEntity>(
    CardEntity_.wallet,
  );

  /// see [WalletEntity.transactions]
  static final transactions =
      obx.QueryBacklinkToMany<TransactionEntity, WalletEntity>(
        TransactionEntity_.wallet,
      );
}
